# Generated by Django 3.1 on 2020-09-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Genre',
            field=models.ManyToManyField(to='user.Genre'),
        ),
    ]
