# Generated by Django 3.1 on 2020-09-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_books_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Age',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
