# Generated by Django 3.1 on 2020-09-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200921_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
