# Generated by Django 3.1 on 2020-09-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='PDF',
            field=models.FileField(blank=True, null=True, upload_to='books/pdfs'),
        ),
        migrations.AlterField(
            model_name='books',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='books/images'),
        ),
    ]
