# Generated by Django 3.1 on 2020-09-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200922_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Description',
            field=models.TextField(null=True),
        ),
    ]
