# Generated by Django 3.1 on 2020-09-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_books_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
