# Generated by Django 3.1 on 2020-09-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200923_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Username',
            new_name='name',
        ),
    ]
