# Generated by Django 3.1 on 2020-09-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='Note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
