# Generated by Django 3.1 on 2020-09-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20200924_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done')], max_length=200, null=True),
        ),
    ]
