# Generated by Django 3.1 on 2020-09-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='DatePayed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
