# Generated by Django 3.1 on 2020-09-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_orders_recieved_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Status',
            field=models.CharField(choices=[('delivering', 'delivering'), ('delivered', 'delivered'), ('returning', 'returning'), ('returned', 'returned')], max_length=200, null=True),
        ),
    ]
