# Generated by Django 3.1 on 2020-09-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20200924_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='returned_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
